[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_archive = false
extra_scripts = pre:scripts/pio_env_fix.py

# WiFi & HTTP Libraries (Essential)
lib_deps =
    adafruit/DHT sensor library@1.4.4
    adafruit/Adafruit Unified Sensor@1.1.14
    knolleary/PubSubClient@2.8
    bblanchon/ArduinoJson@6.21.3
# Build settings
build_flags =
    -DESP_DHT_MIN_READ_INTERVAL_MS=1500UL
    -DESP_MQTT_INTERVAL_MS=10000UL
    -DESP_HTTP_INTERVAL_MS=10000UL
    -DESP_DEVICE_ID=3
    -DESP_DHT_PIN=4
    -DESP_MQTT_PASSWORD=\"esp32\"
    -DESP_MQTT_USER=\"esp32\"
    -DESP_MQTT_TOPIC=\"iot/esp32/suhu\"
    -DESP_MQTT_PORT=1883
    -DESP_WIFI_PASSWORD=\"gratiskok\"
    -DESP_WIFI_SSID=\"Free\"
    -DCORE_DEBUG_LEVEL=0
    -DHTTP_CLIENT_TIMEOUT=5000
    -DMQTT_MAX_PACKET_SIZE=2048
    -DESP_HTTP_INGEST_KEY=\"a49f402364c2ed5eaaf26f57dde011600d0e5e320546ba13d33adf38e500e3fc\"
    -DESP_HTTP_BASE_URL=\"https://espdht.mufaza.my.id\"
    -DESP_HTTP_ENDPOINT=\"/api/http-data\"
    -DESP_MQTT_BROKER=\"espdht.mufaza.my.id\"
    -DESP_HTTP_TLS_INSECURE=1
    -DESP_SENSOR_INTERVAL_MS=5000UL
    -DESP_HTTP_READ_TIMEOUT_MS=5000

# Upload speed
upload_speed = 921600

# Serial port (change based on your system)
# On Windows: COM3, COM4, etc.
# On Linux: /dev/ttyUSB0, /dev/ttyACM0, etc.
# On macOS: /dev/cu.usbserial-*
